### ISSUE TITLE
Fail when run benchmark vpe on baremetal

### ISSUE THREAD

**Issue by xuananh-viosoft** [opnfv/yardstick#1]
I am trying run benchmark with testcase tc_baremetal_http_ipv4_ixload.yaml
but failed with error:

> [2018-01-18 07:54:06,003] [utils:provision_tool:122] WARNING: /opt/nsb_bin/vPE_vnf not found on 10.80.203.11, will try to copy from localhost
> mkdir -p "/opt/nsb_bin"
> Process vnf__0-vPE_vnf-31801:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/ubuntu/validium-nsb-backend/yardstick/yardstick/network_services/vnf_generic/vnf/sample_vnf.py", line 835, in _run
>     cmd = self._build_config()
>   File "/home/ubuntu/validium-nsb-backend/yardstick/yardstick/network_services/vnf_generic/vnf/sample_vnf.py", line 830, in _build_config
>     return self.setup_helper.build_config()
>   File "/home/ubuntu/validium-nsb-backend/yardstick/yardstick/network_services/vnf_generic/vnf/vpe_vnf.py", line 260, in build_config
>     self._build_pipeline_kwargs()
>   File "/home/ubuntu/validium-nsb-backend/yardstick/yardstick/network_services/vnf_generic/vnf/sample_vnf.py", line 234, in _build_pipeline_kwargs
>     tool_path = self.ssh_helper.provision_tool(tool_file=self.APP_NAME)
>   File "/home/ubuntu/validium-nsb-backend/yardstick/yardstick/network_services/vnf_generic/vnf/sample_vnf.py", line 93, in provision_tool
>     return super(VnfSshHelper, self).provision_tool(tool_path, tool_file)
>   File "/home/ubuntu/validium-nsb-backend/yardstick/yardstick/ssh.py", line 505, in provision_tool
>     return super(AutoConnectSSH, self).provision_tool(tool_path, tool_file)
>   File "/home/ubuntu/validium-nsb-backend/yardstick/yardstick/ssh.py", line 434, in provision_tool
>     return provision_tool(self, tool_path, tool_file)
>   File "/home/ubuntu/validium-nsb-backend/yardstick/yardstick/network_services/utils.py", line 125, in provision_tool
>     connection.put(tool_path, tool_path)
>   File "/home/ubuntu/validium-nsb-backend/yardstick/yardstick/ssh.py", line 489, in put
>     return super(AutoConnectSSH, self).put(files, remote_path, recursive)
>   File "/home/ubuntu/validium-nsb-backend/yardstick/yardstick/ssh.py", line 389, in put
>     scp.put(files, remote_path, recursive)
>   File "/home/ubuntu/.validium-env/local/lib/python2.7/site-packages/scp.py", line 154, in put
>     self._send_files(files)
>   File "/home/ubuntu/.validium-env/local/lib/python2.7/site-packages/scp.py", line 228, in _send_files
>     (mode, size, mtime, atime) = self._read_stats(name)
>   File "/home/ubuntu/.validium-env/local/lib/python2.7/site-packages/scp.py", line 218, in _read_stats
>     stats = os.stat(name)
> OSError: [Errno 2] No such file or directory: '/opt/nsb_bin/vPE_vnf'

How can I build out vPE_vnf or any other workaround? Please help me
Thanks.

**Comment by elfiesmelfie** [comment]
Hi, 

Please send a post to the mailing list [1] with "[yardstick]" in the subject

[1] opnfv-tech-discuss@lists.opnfv.org

Emma
